kind: pipeline
name: default

pipeline:
  build:
    secrets: [ npm_token, npm_registry ]
    image: 250ok/node:latest
    environment:
      - NODE_ENV=${NODE_ENV} # https://github.com/nodejs/docker-node/blob/madocker-comster/docs/BestPractices.md
    commands:
      - npm config set $NPM_REGISTRY:_authToken=$NPM_TOKEN
      - npm install --unsafe-perm --quiet --registry http:$NPM_REGISTRY
      - rm ~/.npmrc
      - npm test
    when:
      branch:
        exclude: [ develop ]

  build-dev:
    secrets:
      - source: npm_dev_token
        target: npm_token
      - source: npm_dev_registry
        target: npm_registry
    image: 250ok/node:latest
    environment:
      - NODE_ENV=${NODE_ENV} # https://github.com/nodejs/docker-node/blob/madocker-comster/docs/BestPractices.md
    commands:
      - npm config set $NPM_REGISTRY:_authToken=$NPM_TOKEN
      - npm install --unsafe-perm --quiet --registry http:$NPM_REGISTRY
      - npm test
      - "PACKAGE_VERSION=$(cat package.json | grep version | head -1 |  awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - "PACKAGE_NAME=$(cat package.json | grep name | head -1 |  awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - npm unpublish --force --registry http:$NPM_REGISTRY $PACKAGE_NAME@$PACKAGE_VERSION
      - npm publish --registry http:$NPM_REGISTRY
      - rm ~/.npmrc
    when:
      branch: [ develop ]

  npm-publish:
    image: plugins/npm
    secrets: [ npm_token ]
    when:
      event: [ tag ]
      success: true

  trigger-builds:
    image: 250ok/downstream
    server:
      from_secret: drone_downstream_url
    ignore_pending: true
    fork: true
    repositories:
      - 250ok/integration@master
      - 250ok/mod-utils@master
      - 250ok/mbp-metadata@master
      - 250ok/ds-intake-service@master
      - 250ok/ds-datasync@master
      - 250ok/ds-publisher@master
      - 250ok/ds-feed-generator@master
      - 250ok/data-service-monitor@master
      - 250ok/service-api@master
    token:
      from_secret: downstream_token
    when:
      event: [ tag ]
      success: true

  trigger-dev-builds:
    image: 250ok/downstream
    server:
      from_secret: drone_downstream_url
    ignore_pending: true
    fork: true
    repositories:
      - 250ok/integration@develop
      - 250ok/mod-utils@develop
      - 250ok/mbp-metadata@develop
      - 250ok/ds-intake-service@develop
      - 250ok/ds-datasync@develop
      - 250ok/ds-publisher@develop
      - 250ok/ds-feed-generator@develop
      - 250ok/data-service-monitor@develop
      - 250ok/service-api@develop
    token:
      from_secret: downstream_token
    secrets: [ downstream_token ]
    when:
      branch: [ develop ]
      event: [ push ]
      success: true